### ISSUE TITLE
Goonj Phase 4.1 Small Scale Implementation and Integration changes

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#105]
Goonj Aug 2024 change requirements [sheet](https://docs.google.com/spreadsheets/d/1uA1AWE6ngjHiTeaLU46Fb2mQV6ZpenyGZjImoT8hLIg/edit?usp=sharing)

Goonj 4.1 Phase Technical requirements [sheet](https://docs.google.com/spreadsheets/d/19hf-T7mSn922qZcZQQMtZW2VQaaseQNZ-B2mzcMbDLk/edit?usp=sharing)

---------------------------------------------------------

### Deployment Steps:
**App Changes :**
1. Take backup of goonj bundle
2. Upload bundle from **gvamp_uat** to **goonj** organisation
3. Handle update of lastModifiedDateTime for reportCards and dashboardFilters for Prod **Goonj** Org

```sql

reset role;

set role goonj;

-- No fix needed for below entities

select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_section order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_section_card_mapping order by last_modified_date_time desc;
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard order by last_modified_date_time desc;

-- Fix needed for report_card
select organisation_id, last_modified_date_time, age(last_modified_date_time, created_date_time) from report_card order by last_modified_date_time desc;
-- 356 2024-10-14 11:50:08.083 +00:00 for report_card

-- '2024-10-14 11:33:10.628 +00:00'

--update report_card
--set last_modified_date_time = '2024-09-26 15:21:31.657 +00:00'::timestamptz+ (random() * 1000 * (interval '1 millisecond'))
--where organisation_id = 356 and last_modified_date_time >= '2024-10-14 11:33:10.628 +00:00'::timestamptz;

-- Fix needed for dashboard_filter
select last_modified_date_time, age(last_modified_date_time, created_date_time) from dashboard_filter order by last_modified_date_time desc;
-- 356 '2024-10-14 11:12:10.628 +00:00' for dashboard_filter

--update dashboard_filter
-- set last_modified_date_time = '2024-09-26 15:21:31.657 +00:00'::timestamptz+ (random() * 1000 * (interval '1 millisecond'))
-- where organisation_id = 356 and last_modified_date_time >= '2024-10-14 11:12:10.628 +00:00'::timestamptz;


```

**Integration Changes:**
1. Stop Prod integration Service
2. Take a backup of prod integraion bundle
4. Upload bundle from uat (from staging env) to prod 
5. Select **avni_int** db and execute below query, On Production RDS  :
```sql
UPDATE public.integration_system_config
SET value = 'https://s3.ap-south-1.amazonaws.com/prod-user-media/goonj/'
WHERE integration_system_id = 2 and key = 'avni_s3_url_prefix';
```
6. Deploy new changes of **integration-service** from circle-ci using branch **goonj-sep-2024**

### Post Deployment:
**Branch Merge**:
1. **goonj-sep-2024** in to **goonj-sep-2024-phase3**
2. **goonj-sep-2024** in to **master**
3. Tag the commits appropriately on master branch
4. Sanity testing of integration by moving the dates to 1 day back for all entities
5. Sanity testing of Goonj Prod app on DEA and client

---------------------------------------------------

```[tasklist]
### Tasks
- [ ] https://github.com/avniproject/Goonj/issues/106
- [ ] https://github.com/avniproject/Goonj/issues/107
- [ ] https://github.com/avniproject/Goonj/issues/108
- [ ] https://github.com/avniproject/Goonj/issues/109
- [ ] https://github.com/avniproject/Goonj/issues/110
- [ ] https://github.com/avniproject/Goonj/issues/111
- [ ] https://github.com/avniproject/Goonj/issues/112
- [ ] https://github.com/avniproject/Goonj/issues/113
- [ ] https://github.com/avniproject/Goonj/issues/114
```

**Comment by himeshr** [comment]
@vedfordev Please add notes here, on steps to be performed during Goonj Phase 4.1 and 4.2 go-live, planned for Monday, 21 Oct 2024, 6 30 pm..

Include steps like:
- Handle update of lastModifiedDateTime for reportCards, dashboardFilters for GoonjUAT org and later for PROD
- Merging and tagging
- Sanity testing
- Config should not export env specific info, like url, password, username, etc..
- Mark url prop as secret in local and staging
- Ensure staging int bundle and local int bundle are same to avoid missing out any changes

**Comment by himeshr** [comment]
## Issue details
We found that the last moment changes done to rename concepts created issue with RuleEvaluations in DEA/Client, due to usage of concept names instead of uuid.
[prodConceptNames.txt](https://github.com/user-attachments/files/17627663/prodConceptNames.txt)
[prereleaseConceptNames.txt](https://github.com/user-attachments/files/17627664/prereleaseConceptNames.txt)

## Point of Corrections

<img width="1712" alt="Screenshot 2024-11-05 at 12 00 02 PM" src="https://github.com/user-attachments/assets/497eb0c5-031c-4288-8653-9e5af7552652">


```sql
set role goonj;

select * from form_element where rule SIMILAR TO '%(Any other material given|Details for Any other|Type of school|Was Disclaimer Form Filled|Images|anganwadi|Specify other for objective of work|Quantity \(Dispatched\)|Disclaimer Photographs)%';


-- No Output for below commands

select * from form_element_group where rule SIMILAR TO '%(Any other material given|Details for Any other|Type of school|Was Disclaimer Form Filled|Images|anganwadi|Specify other for objective of work|Quantity \(Dispatched\)|Disclaimer Photographs)%';

select id, uuid, name, decision_rule, validation_rule, edit_form_rule from form where
 decision_rule SIMILAR TO '%(Any other material given|Details for Any other|Type of school|Was Disclaimer Form Filled|Images|Aanganwadi|Specify other for objective of work|Quantity \(Dispatched\)|Disclaimer Photographs)%'
or validation_rule SIMILAR TO '%(Any other material given|Details for Any other|Type of school|Was Disclaimer Form Filled|Images|Aanganwadi|Specify other for objective of work|Quantity \(Dispatched\)|Disclaimer Photographs)%'
or edit_form_rule SIMILAR TO '%(Any other material given|Details for Any other|Type of school|Was Disclaimer Form Filled|Images|Aanganwadi|Specify other for objective of work|Quantity \(Dispatched\)|Disclaimer Photographs)%';

```
[CorrectionSqlOutput.txt](https://github.com/user-attachments/files/17627692/CorrectionSqlOutput.txt)


## Correction to be done
- Modify the concept names with UUID in the affected formElement rules
- Rerun the query and confirm that there are no more instances found for them
- Test in gvamp_uat org
- Upload bundle from gvamp_uat to production
- Sanity of Prod

**Comment by vedfordev** [comment]
@himeshr  only find two images rule need to change
```sql
select f.name,feg.name,fe.name,fe.display_order,
       f.is_voided,
       feg.is_voided,
       fe.is_voided
from form_element fe
         join form_element_group feg on fe.form_element_group_id = feg.id
         join form f on feg.form_id = f.id
where fe.rule SIMILAR TO '%(Details for Any other|Type of school|Was Disclaimer Form Filled|Images|Aanganwadi|Specify other for objective of work|Quantity \(Dispatched\)|Disclaimer Photographs)%'
and f.is_voided = false
and fe.is_voided = false
and feg.is_voided = false
;

```
