### ISSUE TITLE
Additional Dispatch Driver and Delivery details

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#115]
### Additional data in Dispatch Details form
In dispatch registration information the following details which salesforce is sending should also be shown:-
1. Driver Name, 
2. Vehicle Number, 
3. Driver Contact Number
4. Photograph - to upload 4-5 photographs of the truck loading.

## Form Fields
```
""Driver Name""
""Driver Contact Number""
""Vehicle Number""
""Loading And Truck Images""
```

## API Fields
```
"
""DriverName""
""DriverContactNumber""
""VehicleNumber""
""LoadingAndTruckImagesLink"" :- links of images separated by " ; "
```

[SampleDispatchResponseNew.json](https://github.com/user-attachments/files/17184137/SampleDispatchResponseNew.json)

## Tech approach to sync the Photograph URLs in Avni-Goonj integration service, for each dispatch:
- validate each photograph URL to confirm that it is downloadable
- If validation success, incude it in the Upsert Dispatch request body
- Else, add an DecisionConcept to Upsert Dispatch request body. Ex: "InvalidPhotographURLsReceived": "true"
- Invoke the Upsert Dispatch API call on Avni

This would ensure that we are able to sync the data to Avni, even when there are issue with the Photograph URLs. And the "InvalidPhotographURLsReceived" decision concept would also enable us to monitor errored Dispatch entities using a Metabase report.

**Comment by vedfordev** [comment]
### mapping meta data

```sql
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, about, data_type_hint, integration_system_id,
                                     mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'DriverName', 'Driver Name', null, null, 2, 2, 1, uuid_generate_v4(), DEFAULT);

INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, about, data_type_hint, integration_system_id,
                                     mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'DriverContactNumber', 'Driver Contact Number', null, null, 2, 2, 1, uuid_generate_v4(), DEFAULT);

INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, about, data_type_hint, integration_system_id,
                                     mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'VehicleNumber', 'Vehicle Number', null, null, 2, 2, 1, uuid_generate_v4(), DEFAULT);
```

### integration_system_config  (Change for production accordingly)

```sql
INSERT INTO public.integration_system_config (id, integration_system_id, key, value, uuid, is_voided, is_secret)
VALUES (DEFAULT, 2, 'avni_s3_url_prefix', 'https://s3.ap-south-1.amazonaws.com/prod-user-media/gvamp_uat/', uuid_generate_v4(), false,
        false);
```

**Comment by himeshr** [comment]
New format of ImageLinks info in Dispatch response

```json
"ImageLinks" : [
        {
          "UniqueId":"someExampleID1",
          "Link" : "ImageLink1"
          
        },...
]
```

This is easier to create Image on Avni-server for the org with a specific uuid generated from the UniqueId value and then use the same while upserting the Dispatch.


## Pseudocode:
- For each dispatch status receivied in goonj getDispatches api response
- - If, it has image links, 
- - - fetch dispatch from Avni if it already exists using salesforce uniqueID
- - - compare goonj and avni responses, and make a list of missing images in avni comparing with mediaUrlsList and image uniqueIds(using getUniqueUUIDFORImageUniqueID), in-case new dispatch, all images are considered missing
- - - For each missing image in avni
- - - - Download image from salesforce into temp folder, (getUniqueUUIDFORImageUniqueID).png/.jpeg/.jpg
- - - - Create mediaUploadURL on avni, using imageUniqueId converted into UUIDv5 (getUniqueUUIDFORImageUniqueID) 
- - - - Upload from temp folder to avni using upload presigned url, save the response url
- - - - Add response urls to mediaUrlsList
- - - - END FOR 
- - - Set the images Multi Media concept to have the value of mediaUrlsList
- - - Invoke POST Subject call for dispatch 

## Addn info

"ImageLinks" : [
        {
          "UniqueId":"someExampleID1",
          "Link" : "ImageLink1"
          
        },...
]

getUniqueUUIDFORImageUniqueID() {
 => someExampleID1 => someExampleID1-UUID	
}

### References:
https://www.baeldung.com/java-generate-same-uuid-from-string#the-given-input-is-a-free-form-string
https://github.com/avniproject/avni-client/blob/master/packages/openchs-android/src/service/MediaQueueService.js#L120

**Comment by himeshr** [comment]
## Unit tests for Images functionality 

### Inputs for all tests
- Dispatch current images list (avniImgUrls)
- new salesforce images list, (goonjImgUrls)

### Expected output for each test
- Final images urls list actualImgUrls = [imUrl1, imgUrl2, imgUrl3]

### Test cases
| avniImgUrls 	| goonjImgUrls     	| actualImgUrls      	| operation                             	|
|-------------	|------------------	|--------------------	|---------------------------------------	|
| []          	| [img1,img2]      	| [imgUrl1, imgUrl2] 	| Create new images                     	|
| [img1,img2] 	| []               	| []                 	| Delete all old images                 	|
| [img1,img2] 	| [img1,img2,img3] 	| [img1,img2,img3]   	| Create some new,  retain others       	|
| [img1,img2] 	| [img1,img3]      	| [img1,img3]        	| Delete few, create few, retain others 	|
| [img1,img2] 	| [img3,img4]      	| [img3,img4]        	| Delete all, create few                	|

**Comment by vedfordev** [comment]
### Task to be done
- [x] Handle for png and jpeg
- [x] make **AVNI_MEDIA_SOURCE** configurable
- [ ] write test cases for all goonjMediaService methods called in DispatchService.processImages()

**Comment by himeshr** [comment]
## Test Results:

https://app.avniproject.org/#/app/subject?uuid=3af29c87-fd78-492a-8b0e-9b8f57a0fc8e
<img width="593" alt="Screenshot 2024-10-15 at 2 51 43 PM" src="https://github.com/user-attachments/assets/068582d0-bd5c-4ba1-b2dd-8f900c768cfa">
<img width="1606" alt="Screenshot 2024-10-15 at 2 52 11 PM" src="https://github.com/user-attachments/assets/cc62bc5f-5cdc-4e5f-89d1-c73a21724e27">
<img width="1119" alt="Screenshot 2024-10-15 at 2 52 33 PM" src="https://github.com/user-attachments/assets/bceb37e8-c76e-465b-b693-3bf0618b8290">
