### ISSUE TITLE
Goonj Redesign

### ISSUE THREAD

**Issue by BEULAHEVANJALIN** [avniproject/Goonj#46]
- [x] Go through existing implementation - Goonj UAT in prod
- [x] Go through expected prototype - https://docs.google.com/document/d/13ew3SPYo5khSq-esoyMTzinI8xxHDo_MHhJtItte9Mw/edit, in Goonj Demo (prod)
- [x] Create an organisation in staging with name Goonj Redesign similar to Goonj Demo for our work
- [x] Go through API documentation to ensure the field names are an exact match to what we create in Goonj Redesign
- [x] Understanding avni-integration-service code base
- [x] Implementing forms and fields in Goonj Redesign

Modeling in Avni for redesigned implementation:
https://docs.google.com/spreadsheets/d/1TiccUzEJ6qNRlT2SUC9_FzR_ZD3WU9Xh/edit#gid=247862756
