### ISSUE TITLE
Goonj Go-Live

### ISSUE THREAD

**Issue by himeshr** [avniproject/Goonj#66]
## Goal
This card prepares everything to go live for the pilot in two states of Maharashtra ~and Kerala~

## Reference sheet:
https://docs.google.com/spreadsheets/d/1qs1f-hjXeReuC-wg6R3780wik9omW9eofsjI8lGjk5E/edit

## Goonj Side Go-live document
https://docs.google.com/document/d/1iBL9pbtRfWD2R5107FvbU9BUzlhkdLf7-yUb_sSRWgM/edit?usp=sharing

Requirements from customer
- [x] Locations #67
- [x] Account name associated with each user
- [x] User and catchment/location mapping
- [x] Production salesforce credentials for prod integration service to use
- [x] Sync start date and cron job details

Steps:
- [x] Download bundle without locations
- [x] Upload bundle without locations
- [x] Create locations #67
- [x] Create Catchments
- [x] Create users with appropriate catchment and syncConceptValue configurations
- [x] Configure UserGroups (Dashboards and permissions) (FieldStaff, FieldSupervisior, GoonjAdmin, etc..)
- [x] Assign Users to UserGroups
- [x] Void dashboards and related entities which were actually voided in Staging env (do same for report_cards and dashboard_sections and dashboard_section_mappings)
- [x] Setup accounts (sync concept values) for users
- [x] Create Goonj Avni API user for integration service to use (with no catchment & sync concept value)
- [x] Salesforce system users (for delete, etc)
- [x] Configure new credentials (Prod Avni Goonj Api user and password. Salesforce Prod system credentials.Tasks to be run and their frequency)
- [x] Deploy latest integration code to prod int server
- [x] Take the integration bundle from UAT and apply to Prod
- [x] Copy integration config for goonj from integration system config db (from staging avni-int)
- [x] Setup Integration system Monitoring and alert. Configure Errors /  Exceptions to be ignored.
- [x] Prod integration should start using the prod api. Sanity testing using Prod APK for Goonj prod implementation.

Async Task (#67)
- [x] Upload locations for Maharashtra
~- [ ] Upload locations for Kerala~

** Note ** 
For this pilot we are going with single Avni org for multiple states (MH and Kerala in this case). Separately we would discuss the scale up approach to go across all the states in the country.
